services:
  - type: web
    name: pepe-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: 7429224365:AAEVw5fDYIytSO54rXJOsWOBpQ8tatHOfOE
        sync: false
      - key: 463008392
        sync: false
